### PR TITLE
Add NegativeFromTo predicate

### PR DESCRIPTION
**Pull request by futtetennista**
Adds a new predicate that allows to check that a given number is greater or equal than a _negative_ number and less than a positive number.

I implemented the original version of this code based on an old version of the library so props go to @kcsongor for updating the code using `throwRefineOtherException`.

### CODE REVIEW

**Comment by chessai** [comment]
I'm going to merge this now. In version 4.x refined is going to have better support for numeric predicates with negative numbers

**Comment by chessai** [comment]
Thank you!

**Comment by futtetennista** [comment]
> In version 4.x refined is going to have better support for numeric predicates with negative numbers

Great and thank you for this super-useful library.

**Comment by chessai** [comment]
All positive emojis granted unto you

**Pull request merged**
