### PR TITLE
ensure that arbitrary for Refined will terminate

### PR DESCRIPTION
**Pull request by chessai**

### CODE REVIEW

**Comment by chessai** [comment]
@symbiont-joseph-kachmar this is what i came up with to resolve #40. let me know what you think.

**Comment by chessai** [comment]
most recent checks fail because i cancelled the builds (just changelog entry)

**Comment by symbiont-joseph-kachmar** [comment]
Sorry for the delay, but I think this makes sense!

I wish there was a better alternative to calling `error` here but I can't think of one, and this is primarily intended for test code anyway so it's not so bad.

**Comment by chessai** [comment]
well, luckily QuickCheck catches the errors, and we try to provide a decent error message here. but i agree that i wish you could fail inside of Gen instead of delegating the failure to the top level. maybe i don't actually wish that, but here it would be nice.

**Pull request merged**
